name: CI/CD NewIntent

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Verify build output
        run: ls -la build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run security check
        run: npm audit

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run static analysis
        run: npm run static-analysis

  deploy:
    runs-on: ubuntu-latest
    needs: [build, tests, lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build

  verify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Verify deployment
        run: |
          echo "Verifying deployment"
          for i in {1..5}; do
            curl -I https://haroldstx.github.io/CI-CD-New-Intent/ | grep "200 OK" && break || sleep 10
          done
